#! /bin/sh
# /etc/init.d/recopter

touch /var/lock/recopter

case "$1" in
start)
echo "Starting RasPi I2C communication with recopter ... "
python /home/pi/develop/recopter/raspberry_pi/i2c/recopter.py > /dev/null &
;;
stop)
echo "Killing RasPi I2C communication with recopter ..."
killall python
;;
*)
echo "Usage: /etc/init.d/recopter {start|stop}"
exit 1
;;
esac
exit 0
